title = "08-Broadcast_2"
author = "huangx607087"
difficulty = "Medium+"
flag = "susctf{rlwe_is_post_quantum_secure_but_lfsr_not_so_please_use_os_dot_urandom_instead!}"

description = """
> 本题目需使用 `nc` 命令进行连接，不支持浏览器打开，点击查看[nc使用教程](https://ctf.xidian.edu.cn/wiki/13)

上一次是因为方法不对所以才被你用滤波器听到了flag！可恶，你这次运气没那么好了！

我发现广播flag不太安全，因此我决定广播token，根据token换flag! 不过广播内容依然是还是加密的，并且依然是后量子加密的！以及，这一次:)，我觉得消息已经完全淹没在噪声中了，看你怎么听到！

"""

[container]
port = 9999
cpu = 4 # 0.1*1个cpu
memory = 450 # unit: MiB
storage = 450 # unit: MiB **注意：包含镜像大小**

[attachments]
path = ["build/src/task.py"]
