title = "07-ECRSA"
author = "huangx607087"
difficulty = "Medium"
flag = "susctf{[GUID]}"

description = """
> 本题目需使用 `nc` 命令进行连接，不支持浏览器打开，点击查看[nc使用教程](https://ctf.xidian.edu.cn/wiki/13)

你知道 ECRSA 是什么算法吗？
"""

[container]
port = 9999
cpu = 4 # 0.1*1个cpu
memory = 450 # unit: MiB
storage = 450 # unit: MiB **注意：包含镜像大小**

[attachments]
path = ["build/src/task.py"]
