title = "04-Broadcast_1"
author = "huangx607087"
difficulty = "Easy"
flag = "susctf{[GUID]}"

description = """
> 本题目需使用 `nc` 命令进行连接，不支持浏览器打开，点击查看[nc使用教程](https://ctf.xidian.edu.cn/wiki/13)

各位听好了，我要开始广播我的flag了，不过是加密的，并且是抗量子密码加密的！:D

1994年，Shor提出了量子计算算法，主要用于解决大整数质因数分解和离散对数问题。该算法通过量子并行性与量子傅里叶变换将问题复杂度从指数级降至多项式级，直接威胁RSA、ECC等公钥加密体系的安全性

---
「我每天带3个2048位的大整数去橘园食堂吃饭。」--MaPl,susctf2024

「我每天带2048个3位的小整数去橘园食堂吃饭。」--huangx607087,susctf2025

"""

[container]
port = 9999
cpu = 4 # 0.1*1个cpu
memory = 450 # unit: MiB
storage = 450 # unit: MiB **注意：包含镜像大小**

[attachments]
path = ["build/src/task.py"]
